name: marionette
description: A Dart code generation library that creates type-safe classes from Firebase Remote Config default files.
version: 1.0.4
homepage: https://github.com/1qlabs/marionette

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  args: ^2.3.0
  dart_style: ^3.1.0
  interpolation: ^2.1.2
  path: ^1.8.1
  recase: ^4.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0

scripts:
  # Test code generation with validation
  test-generate: dart run scripts/test_generation.dart

  # Clean generated files
  clean: rm -f example_output.dart example_generated.dart *.g.dart

  # Run full test suite (if tests exist)
  test-all: dart test

  # Lint the code
  lint: dart analyze

  # Format the code
  format: dart format lib/ bin/ scripts/

  # Run all checks (format, lint, test-generate)
  check: dart format lib/ bin/ scripts/ && dart analyze && dart run scripts/test_generation.dart
